server:
  port: 9081

spring:
  application:
    name: raft-kv-store-node1

raft:
  group-id: kv-store-group
  node-id: 127.0.0.1:8081:0
  endpoint: 127.0.0.1:8081
  port: 8081
  http-port: 9081
  peers: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083
  data-dir: D:/project/Claudecode/raft-kv-store/data/node1
  initializer: true
  read-timeout: 5000
  write-timeout: 5000
  election-timeout-ms: 1000  # 选举超时，本地开发建议 1000ms，生产环境建议 150-300ms

logging:
  level:
    com.raftkv: DEBUG
    com.alipay.sofa.jraft: INFO
