server:
  port: 9083

spring:
  application:
    name: raft-kv-store-node3

raft:
  node-id: 127.0.0.1:8083
  http-port: ${server.port}
  peers: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083
  peer-http-endpoints: 127.0.0.1:9081,127.0.0.1:9082,127.0.0.1:9083
  data-dir: D:/project/Claudecode/raft-kv-store/data/node3
  initializer: false

logging:
  level:
    com.raftkv: DEBUG
    com.alipay.sofa.jraft: INFO
