server:
  port: 9082

spring:
  application:
    name: raft-kv-store-node2

raft:
  node-id: 127.0.0.1:8082
  http-port: ${server.port}
  peers: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083
  peer-http-endpoints: 127.0.0.1:9081,127.0.0.1:9082,127.0.0.1:9083
  data-dir: D:/project/Claudecode/raft-kv-store/data/node2
  initializer: false

  # 读超时（毫秒）
  read-timeout: 5000

  # 写超时（毫秒）
  write-timeout: 5000

  # 选举超时（毫秒）
  election-timeout-ms: 1000

  # 快照触发间隔（日志条数）
  snapshot-log-index-margin: 10000

  # 快照触发间隔（秒）
  snapshot-interval-secs: 3600

logging:
  level:
    com.raftkv: DEBUG
    com.alipay.sofa.jraft: INFO
