server:
  port: 8083

spring:
  application:
    name: raft-kv-store-node3

raft:
  group-id: kv-store-group
  node-id: 127.0.0.1:8083:0
  endpoint: 127.0.0.1:8083
  port: 8083
  peers: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083
  data-dir: D:/project/Claudecode/raft-kv-store/data/node3
  initializer: false
  read-timeout: 3000
  write-timeout: 3000

logging:
  level:
    com.raftkv: DEBUG
    com.alipay.sofa.jraft: INFO
